version: '3'
services:
  # Node.js Application
  nodejs-app:
    image: authentication-image:latest
    container_name: authentication-container
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: npm start
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
