version: '3'
services:
  angular-app:
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - authentication-service

  openai-service:
    build:
      context: ./services/openai
      dockerfile: Dockerfile
    container_name: openai-container
    ports:
      - "5000:5000"
    command: npm start
    depends_on:
      - postgres
      - authentication-service
  # Node.js Application
  authentication-service:
    build:
      context: ./services/authentication
      dockerfile: Dockerfile
    container_name: authentication-container
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: npm start
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
