openapi: 3.0.0
info:
  title: Sample Node.js Swagger API
  description: A sample Node.js web API with Swagger documentation
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/hello:
    get:
      summary: Get a hello message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
