GET http://localhost:3000/health

###

# endpoint for authentication
# Endpoint returns jwt
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "test2",
    "password": "test2"
}

###

POST http://localhost:3000/auth/verify HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWF0IjoxNjk1OTMxMjA0LCJleHAiOjE2OTU5MzQ4MDR9.BPBgVZD3q1PE9hW-BFFFaLUGCq9Sd55PSveSprBvRDU"
}

###

#endpoint for registration
# Endpoint returns 201 (created)
POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "username": "test2",
    "email": "email@email",
    "password": "test2"
}